Ignorando el sesgo/bias y asumiendo activación sigmoidal implementar la siguiente red neuronal en NumPy

https://gadictos.com/neural-network-pt1/
<img src="https://gadictos.com/wp-content/uploads/2019/05/bp1.png">

In [1]:
import numpy as np

In [2]:
def sigmoid(X):
    return 1/(1+np.exp(-X))

sigmoid(np.array([2,3,4]))

array([0.88079708, 0.95257413, 0.98201379])

In [3]:
Wc1 = np.array([
   [0.9,0.3,0.2],
   [0.8,0.5,0.4],
   [0.1,0.6,0.7]
])

In [4]:
Wc2 = np.array([0.3,0.5,0.9])

In [5]:
# 4 observaciones, 3 variables
X = np.array([
      [1,0,1],
      [1,2,3],
      [4,5,6],
      [6,7,8],
])

### Forward-propagation(inferencia, prediccion, o estimacion)


In [6]:
H = np.matmul(X,Wc1)

In [7]:
X.shape

(4, 3)

In [8]:
Wc1.shape

(3, 3)

In [9]:
H.shape

(4, 3)

In [10]:
H

array([[ 1. ,  0.9,  0.9],
       [ 2.8,  3.1,  3.1],
       [ 8.2,  7.3,  7. ],
       [11.8, 10.1,  9.6]])

In [11]:
A = sigmoid(H)

In [12]:
A

array([[0.73105858, 0.7109495 , 0.7109495 ],
       [0.94267582, 0.95689275, 0.95689275],
       [0.99972542, 0.99932492, 0.99908895],
       [0.9999925 , 0.99995892, 0.99993228]])

In [13]:
y_aprox = sigmoid(np.matmul(
    A,Wc2
))

In [14]:
y_aprox

array([0.77112013, 0.83513309, 0.84537273, 0.8455238 ])

In [15]:
def g(X):
    return sigmoid(np.matmul(X,Wc1))

In [16]:
def f(g):
    return sigmoid(np.matmul(g,Wc2))

In [17]:
y_aprox = f(g(X))

In [18]:
y_aprox

array([0.77112013, 0.83513309, 0.84537273, 0.8455238 ])

#### Orientado a objetos

In [19]:
class RedNeuronal:
    def __init__(self):
        self.Wc1 = np.array([
                   [0.9,0.3,0.2],
                   [0.8,0.5,0.4],
                   [0.1,0.6,0.7]
                ])

        self. Wc2  = np.array([0.3,0.5,0.9])

    def forward_propagation(self,X):
        A = sigmoid(np.matmul(X,self.Wc1))
        y_aprox = sigmoid(np.matmul(A,self.Wc2))

        return y_aprox

In [20]:
red = RedNeuronal()
red.forward_propagation(X)

array([0.77112013, 0.83513309, 0.84537273, 0.8455238 ])

[0.73105858 0.78583498 0.68997448]

In [21]:
class RedNeuronal:
    def __init__(self):
        # 1 fila por neurona , 1 columna por variable de entrada
        self.Wc1 = np.array([
            [0.8,0.2],
            [0.4,0.9],
            [0.3,0.5]    
        ])

        # 1 elemento para cada neurona intermedia
        self. Wc2  = np.array([0.3,0.5,0.9])

    def forward_propagation(self,X):
        print(X.shape)
        print(self.Wc1.T.shape)
        A = sigmoid(np.matmul(X,self.Wc1.T)) # 1 fila por observacion, 1 columna por representacion intermedia [4,3]
        print(A)
        print(A.shape)
        y_aprox = sigmoid(np.matmul(A,self.Wc2)) # 1 fila por observacion,  1 unica salida [4,1]
        print(y_aprox.shape)
        
        return y_aprox

In [22]:
# 4 observaciones, 2 variables
X = np.array([
      [1,1],
      [1,2],
      [4,5],
      [6,7],
])

In [23]:
red = RedNeuronal()
y_aprox = red.forward_propagation(X)

(4, 2)
(2, 3)
[[0.73105858 0.78583498 0.68997448]
 [0.76852478 0.90024951 0.78583498]
 [0.98522597 0.99776215 0.97587298]
 [0.99797468 0.99983344 0.9950332 ]]
(4, 3)
(4,)


In [24]:
y_aprox

array([0.77438027, 0.80026216, 0.84194007, 0.84485948])

### Ejercicio Calculado salida de un MLP

<img src='./imgs/red1.png'>

In [25]:
class RedNeuronal:
    def __init__(self):
        self.Wc1 = np.array([
                   [5.0, -2.0],
                   [7.0, -3.0],
                   [-8.0, 1.0]
                ])

        self. Wc2  = np.array([7.0, 5.0, -6])

    def forward_propagation(self,X):
        A = sigmoid(np.matmul(X,self.Wc1))
        A = np.hstack((A, np.ones((4,1))))
        y_aprox = sigmoid(np.matmul(A,self.Wc2))

        return A, y_aprox

In [26]:
X = np.array([
      [1,1,1],
      [1,2,1],
      [4,5,1],
      [6,7,1],
])

In [27]:
red = RedNeuronal()
H, y_aprox = red.forward_propagation(X)

In [28]:
H

array([[9.82013790e-01, 1.79862100e-02, 1.00000000e+00],
       [9.99983299e-01, 9.11051194e-04, 1.00000000e+00],
       [1.00000000e+00, 2.78946809e-10, 1.00000000e+00],
       [1.00000000e+00, 1.26641655e-14, 1.00000000e+00]])

In [29]:
y_aprox

array([0.72392747, 0.73193032, 0.73105858, 0.73105858])

- Para esta primera red, la característica intermedia con mayor presencia es X3

<img src="https://i.imgur.com/IDFRq5a.png">

In [30]:
class RedNeuronal:
    def __init__(self):
        self.Wc1 = np.array([
                   [8.0, 0.2],
                   [0.4, 0.9],
                   [0.3, 0.5]
                ])

        self. Wc2  = np.array([0.3, 0.5, 0.9])

    def forward_propagation(self,X):
        A = sigmoid(np.matmul(X,self.Wc1.T))
        y_aprox = sigmoid(np.matmul(A,self.Wc2))

        return A, y_aprox

In [31]:
X = np.array([[1, 1]])

In [32]:
red = RedNeuronal()
H, y_aprox = red.forward_propagation(X)

In [33]:
H

array([[0.99972542, 0.78583498, 0.68997448]])

In [34]:
y_aprox

array([0.78815037])

- Para esta segunda red, la característica intermedia con mayor presencia es X1