#### BackPropagation
Carlos Garcia - 21000475

<img src="./imgs/red.png">

In [1]:
import numpy as np

In [2]:
x = np.array([[3, 10]], dtype = 'float')

In [3]:
h3 = np.array([
               [-0.23, 0.22, 0.77],
               [0.9, 0.88, -0.4]
            ])


h2 = np.array([
               [-0.3, 0.62, 0.45],
               [0.45, 0.57, 0.48],
               [0.65, 0.58, -0.45]
            ])

h1 = np.array([
               [0.3, 0.46, 0.02],
               [0.22, -0.7, 0.65],
               [0.65, 0.9, 0.34]
            ])

In [4]:
delta_h3 = np.matmul(x, h3)
delta_h2 = np.matmul(delta_h3, h2)
delta_h1 = np.matmul(delta_h2, h1)

In [5]:
layers = [delta_h3, delta_h2, delta_h1]
i = 3
for layer in layers:
    n = np.argmax(layer.flatten())
    print('\nHidden Layer {} ---------------'.format(i))
    print(layer)
    print('Neuron with most error is: {}'.format(n+1))
    i -= 1


Hidden Layer 3 ---------------
[[ 8.31  9.46 -1.69]]
Neuron with most error is: 2

Hidden Layer 2 ---------------
[[0.6655 9.5642 9.0408]]
Neuron with most error is: 2

Hidden Layer 1 ---------------
[[8.180294 1.74791  9.303912]]
Neuron with most error is: 3


### XOR con ANN

In [70]:
def relu(x):
    return np.where(x > 0.0, x, 0.0)    

In [71]:
def append_bias(x):
    return np.hstack((x, np.ones((x.shape[0], 1))))

In [85]:
def initialize_weights(input_features, layers):
    #layers contain the number of layers neurons and is equal to the length of hidden + output layers
    weights = dict()
    bias = 1
    neurons = input_features + bias
    for l in range(1, len(layers) + 1):
        weights['W{}'.format(l)] = np.random.normal(loc = 0, scale = 0.1, size = (neurons, layers[l-1]))
        neurons = layers[l-1] + bias        
        
    return weights    

In [117]:
x = np.array([[1, 1],
              [1, 0],
              [0, 1],
              [0, 0]], dtype = 'float')

y = np.array([0,1,1,0]).reshape(4,1)

print(x)
print(x.shape)
print(y)

[[1. 1.]
 [1. 0.]
 [0. 1.]
 [0. 0.]]
(4, 2)
[[0]
 [1]
 [1]
 [0]]


In [90]:
weights = initialize_weights(x.shape[1], [2,2,1])
weights

{'W1': array([[-0.10507131, -0.18016528],
        [-0.10829563,  0.0695341 ],
        [ 0.11081245, -0.05081181]]),
 'W2': array([[-0.23582609, -0.19435048],
        [ 0.03061882,  0.04692732],
        [ 0.09114026,  0.01024636]]),
 'W3': array([[-0.02746457],
        [ 0.03515202],
        [-0.01518075]])}

In [114]:
def forward_propagation(x, weights):
    
    layer = append_bias(x)
    num_layers = len(weights.keys())
    for l in range(1, num_layers):
        Z = np.matmul(layer, weights['W{}'.format(l)])
        A = relu(Z)
        layer = append_bias(A)
        
    Z = np.matmul(layer, weights['W{}'.format(num_layers)])
    return Z

In [116]:
results = forward_propagation(x, weights)
results

array([[-0.01732369],
       [-0.01732573],
       [-0.01730945],
       [-0.01696616]])

In [118]:
def getCost(y_hat, y_real):
    return 1/2 * np.mean(np.power(y_hat - y_real, 2))

In [119]:
getCost(results, y)

0.2588072649626528